#! /bin/bash

if ! [ -f /mnt/sync/conf/sync.conf ]; then
    cp -fv /etc/sync.conf /mnt/sync/conf/
fi

if ! [ -f /mnt/sync/data/ResilioSyncPro.btskey ]; then
    cp -fv /etc/ResilioSyncPro.btskey /mnt/sync/data/
fi

exec /usr/bin/rslsync --nodaemon $*